// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfGw1YTSQvWwCUiU3vs5OWrwlgvv1aKiA',
    appId: '1:201370298534:web:012091707f261050e62c67',
    messagingSenderId: '201370298534',
    projectId: 'noise-safe',
    authDomain: 'noise-safe.firebaseapp.com',
    storageBucket: 'noise-safe.firebasestorage.app',
    measurementId: 'G-F02EV3DH6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJTBYTcETIp_Soe0DjJkmCUg-_BSgz2_Q',
    appId: '1:201370298534:android:b2940ae114f1260ae62c67',
    messagingSenderId: '201370298534',
    projectId: 'noise-safe',
    storageBucket: 'noise-safe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2qn4n5v-Jrelp9qyDlQvXkC5gjqMNB0',
    appId: '1:201370298534:ios:b7b406b935c7cba4e62c67',
    messagingSenderId: '201370298534',
    projectId: 'noise-safe',
    storageBucket: 'noise-safe.firebasestorage.app',
    iosBundleId: 'com.example.noiseSafe1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb2qn4n5v-Jrelp9qyDlQvXkC5gjqMNB0',
    appId: '1:201370298534:ios:b7b406b935c7cba4e62c67',
    messagingSenderId: '201370298534',
    projectId: 'noise-safe',
    storageBucket: 'noise-safe.firebasestorage.app',
    iosBundleId: 'com.example.noiseSafe1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfGw1YTSQvWwCUiU3vs5OWrwlgvv1aKiA',
    appId: '1:201370298534:web:07ab4c047e2e60b2e62c67',
    messagingSenderId: '201370298534',
    projectId: 'noise-safe',
    authDomain: 'noise-safe.firebaseapp.com',
    storageBucket: 'noise-safe.firebasestorage.app',
    measurementId: 'G-FRE7E47P5N',
  );
}
